---
- name: Install packages
  package:
    name: "{{ mysql_community_repo_rpm_url }}"
    state: present

- name: Import GPG key
  rpm_key:
    key: "{{ mysql_community_repo_key_url }}"
    state: present
